### ISSUE TITLE
points sample from which mesh

### ISSUE THREAD

**Issue by jeannotes** [daerduoCarey/partnet_dataset#19]
1. the points sampled from which mesh? objs or normalized obj? seems in some anno-ids there exist no normalized-objs
2. you metion that  "pts-10000.txt"  is " # point cloud directly sampled from the combination of part meshes under `objs/` "
   how do you define combination, merge duplicate vertices?
3. you mention that "sample-points-all-pts-nor-rgba-10000.txt" is "# point cloud directly sampled from the whole ShapeNet model  with labels transferred from `label-10000.txt`" how do you transfer? any scripts

**Comment by daerduoCarey** [comment]
1. please ignore "normalized-objs", which is some legacy stuffs. Points with names "sample-points***" are sampled from ShapeNet original mesh and part labels propagated from the PartNet annotation, while pointsin "pts-***.txt" are directly sampled from PartNet meshes, where some details may be smoothed out compared with the original shapenet mesh due to the annotation process.
2. Just combine the vertices and faces from these obj files.
3. for each point in "sample-points-**" find the closest point in "pts-10000.txt", and just transfer its label.

**Comment by jeannotes** [comment]
@daerduoCarey  when will the leader board be ok? we just train new model and hope to evaluate it. hope we can submit our results

**Comment by daerduoCarey** [comment]
unfortunately, we have no bandwidth to work on that. I don't expect that anytime soon. But we've released the full set of evaluation code that you can test your models. https://github.com/daerduoCarey/partnet_seg_exps.

**Comment by a-maiti** [comment]
Hi, thanks for such a wonderful project. can you point me towards the sampling code which samples 10k points from the mesh? Thanks
